### ISSUE TITLE
Load Test fails with SIGSEGV

### ISSUE THREAD

**Issue by christiaangoossens** [livekit/livekit-cli#56]
When running `livekit-cli load-test`, independant of the amount of subscribers, publishers or other settings, this error occurs:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0x16c9031]

goroutine 235 [running]:
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).nextSample(0xc000474ab0, 0x1)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:77 +0x3f1
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).NextSample(0xc000474ab0)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:54 +0x54
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc00084c680, {0xddd7d78, 0xc000474ab0}, 0x0)
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:395 +0x1c7
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:185 +0x571
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0x16c9031]

goroutine 239 [running]:
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).nextSample(0xc000474c00, 0x1)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:77 +0x3f1
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).NextSample(0xc000474c00)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:54 +0x54
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc00084c820, {0xddd7d78, 0xc000474c00}, 0x0)
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:395 +0x1c7
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:185 +0x571
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0x16c9031]

goroutine 237 [running]:
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).nextSample(0xc000474ba0, 0x1)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:77 +0x3f1
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).NextSample(0xc000474ba0)
	/Users/christiaangoossens/Projects/Livekit/livekit-cli/pkg/provider/h264looper.go:54 +0x54
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc00084c750, {0xddd7d78, 0xc000474ba0}, 0x0)
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:395 +0x1c7
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
	/Users/christiaangoossens/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.3/localsampletrack.go:185 +0x571
```

**Comment by christiaangoossens** [comment]
Solved with 1.0.2
