### ISSUE TITLE
Load tester fails with invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by imredobos** [livekit/livekit-cli#69]
I'm trying to test my Livekit instance using the load tester, but it always almost crashes. Using a small number of publishers and subscribers does not make it crash, like 5 publishers and 10 subscribers, but with more, it basically always crashes.
```panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x2 addr=0x38 pc=0x102d1122c]

goroutine 57048 [running]:
github.com/livekit/server-sdk-go.(*Room).GetParticipants(0x14014ff72c0?)
	github.com/livekit/server-sdk-go@v0.10.3/room.go:199 +0x3c
github.com/livekit/livekit-cli/pkg/loadtester.(*LoadTester).onTrackSubscribed(0x1400c5104d0, 0x1401ba4d200, 0x1401b504f70, 0x1401b3fc790)
	github.com/livekit/livekit-cli/pkg/loadtester/loadtester.go:251 +0x40
github.com/livekit/server-sdk-go.(*RemoteParticipant).addSubscribedMediaTrack(0x1401b3fc790, 0x1401ba4d200, {0x1401a722705, 0x11}, 0x1401bd41260)
	github.com/livekit/server-sdk-go@v0.10.3/remoteparticipant.go:109 +0x268
github.com/livekit/server-sdk-go.(*Room).handleMediaTrack(0x0?, 0x1401ea01380?, 0x140266c26c0?)
	github.com/livekit/server-sdk-go@v0.10.3/room.go:246 +0xd8
github.com/livekit/server-sdk-go.(*RTCEngine).configure.func4(0x14011bc1b60?, 0x0?)
	github.com/livekit/server-sdk-go@v0.10.3/engine.go:171 +0x30
created by github.com/pion/webrtc/v3.(*PeerConnection).onTrack
	github.com/pion/webrtc/v3@v3.1.42/peerconnection.go:461 +0x1d8
➜  ~ livekit-cli --version
livekit-cli version 1.0.2

**Comment by davidzhao** [comment]
this is fixed in v1.0.3, that's just released.
