### ISSUE TITLE
version 1.1.0 [signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0xb0070a]

### ISSUE THREAD

**Issue by nums** [livekit/livekit-cli#80]
Hello, 

it seems that this problem persists on v 1.1.0 :

```shell
Starting load test with 1 publishers, 25 subscribers, room: test-room
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x6 pc=0xb0070a]

goroutine 157 [running]:
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).nextSample(0xc000397050, 0x1)
        /root/livekit-cli/pkg/provider/h264looper.go:77 +0x3ea
github.com/livekit/livekit-cli/pkg/provider.(*H264VideoLooper).NextSample(0xc000397050?)
        /root/livekit-cli/pkg/provider/h264looper.go:54 +0x48
github.com/livekit/server-sdk-go.(*LocalSampleTrack).writeWorker(0xc0004ea820, {0x7fced0085a78, 0xc000397050}, 0x0)
        /root/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220806220401-4ccb94386818/localsampletrack.go:395 +0x1c7
created by github.com/livekit/server-sdk-go.(*LocalSampleTrack).Bind
        /root/go/pkg/mod/github.com/livekit/server-sdk-go@v0.10.5-0.20220806220401-4ccb94386818/localsampletrack.go:185 +0x57b
```

**Comment by davidzhao** [comment]
Did you build the CLI? if so please ensure you have Git LFS set up prior to cloning the repo.

The error indicates the bundled files are incorrect.

**Comment by nums** [comment]
Yes, sorry about that, i have forgotten to install  Git LFS
