### ISSUE TITLE
panic: runtime error: slice bounds out of range [-7:]

### ISSUE THREAD

**Issue by ChenMoGe2** [livekit/livekit-cli#9]
I execute code to use load test and it print panic

code:
```
./livekit-load-tester --url http://10.64.31.31:7880 --api-key=API4TNGcc8K8KXt --api-secret=qDTSklbwfwpEv3y8vhq6emRdnud5hLvbUilmxvz4Bva --room testroom --duration 1m  --publishers 10 --subscribers 10 --identity-prefix tes
```

panic:
```
panic: runtime error: slice bounds out of range [-7:]

goroutine 230 [running]:
github.com/livekit/livekit-cli/pkg/loadtester.(*LoadTester).consumeTrack(0xc000334480, 0xc000238900)
 /root/livekit-cli-main/pkg/loadtester/loadtester.go:186 +0x40c
created by github.com/livekit/livekit-cli/pkg/loadtester.(*LoadTester).onTrackSubscribed
 /root/livekit-cli-main/pkg/loadtester/loadtester.go:171 +0x505
panic: runtime error: slice bounds out of range [-7:]

goroutine 484 [running]:
github.com/livekit/livekit-cli/pkg/loadtester.(*LoadTester).consumeTrack(0xc0004465a0, 0xc0008605a0)
 /root/livekit-cli-main/pkg/loadtester/loadtester.go:186 +0x40c
created by github.com/livekit/livekit-cli/pkg/loadtester.(*LoadTester).onTrackSubscribed
 /root/livekit-cli-main/pkg/loadtester/loadtester.go:171 +0x505
```

**Comment by davidzhao** [comment]
I'm unable to reproduce this. Can you tell me the version of server & cli used? Which OS is the load tester ran on?

**Comment by ChenMoGe2** [comment]
@davidzhao client version 0.6.3server version

**Comment by davidzhao** [comment]
this has been resolved. we are using a new path for load testing
